#!/usr/bin/env node

require('dotenv').config();

const {
  DB_NAME,
  DB_USER,
  DB_PASSWORD,
  DB_HOST,
} = process.env;

// eslint-disable-next-line
console.log(`mysql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}/${DB_NAME}`);
